### ISSUE TITLE
running python3 script on mac os

### ISSUE THREAD

**Issue by mraeclo** [raganmd/blog-td-subprocess#1]
Hello, how is it going?

I am trying to run a python3 from script within touch designer 2019.19.160 on a mac osx 10.13.6 using the subprocces. It has args so what I have so far is 

```
def LookForGenderAndAge():
    # point to our script that we're going to execute
    cmd_python_script = '{}/scripts/AgeGender.py'.format(project.folder)
    # cmd_python_script = '{}/Users/mraeclo/Documents/GitHub/learnopencv/AgeGender/AgeGender.py'.format(project.folder)

    # construct a list of arguments for out external script
    currentFuckface = str(op('currentFuckface').par.value0)
    pathToImage = '/Users/mraeclo/Documents/Touch Designer/RacistPurikura/Fuckfaces_capture/'
    script_args = ['--input', pathToImage + "fuckface" +
                   currentFuckface + ".png", '--fuckface', currentFuckface]

    # set python3 to be used instead of python
    python_exe = '/Library/Frameworks/Python.framework/Versions/3.5/Resources/Python.app'

    # join our python instructions with our scirpt args
    command_list = [python_exe, cmd_python_script] + script_args
    # command_list = ['python', cmd_python_script] + script_args

    # call our script with subprocess
    subprocess.Popen(command_list, shell=False)
    print("finished calling script")
```

Which gives me the following errors

```
Traceback (most recent call last):
  File "/project1/script_extractFeatures", line 8, in onValueChange
  File "/project1/script_extractFeatures", line 32, in LookForGenderAndAge
  File "/Applications/TouchDesigner099.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/Applications/TouchDesigner099.app/Contents/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1541, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```

I tried other paths but they give the same error as the above

Am I pointing to the wrong place?

**Comment by mraeclo** [comment]
The correct path seems to be /Library/Frameworks/Python.framework/Versions/3.5/Resources/Python.app/Contents/MacOS/ but inside there the Python file does not have an extension so I am not being able to call it on TD

**Comment by raganmd** [comment]
You might try the keyword ‘python3’ instead of the path to the app itself. Using. A su process call can be frustrating. Can you saw more about what you’re doing in that script? For clarity, it does have to be completely self contained python.
